### ISSUE TITLE
Error: ToolbarComponent could not be found. Error: Create the class ToolbarComponent below in file: app/Controller/Component/ToolbarComponent.php

### ISSUE THREAD

**Issue by MsPseudolus** [cakephp/debug_kit#166]
Hi. Perplexed by this error. PHP 5.3.3 and Cake 2.2.3.

Here's the full error:

```
Missing Component
Error: ToolbarComponent could not be found.
Error: Create the class ToolbarComponent below in file: app/Controller/Component/ToolbarComponent.php
<?php 
class ToolbarComponent extends Component {
}
Notice: If you want to customize this error message, create app/View/Errors/missing_component.ctp
Stack Trace
#0 /Applications/MAMP/htdocs/kuratur-120813/lib/Cake/Controller/ComponentCollection.php(51): ComponentCollection->load('DebugKit.Toolba...', Array)
#1 /Applications/MAMP/htdocs/kuratur-120813/lib/Cake/Controller/Controller.php(585): ComponentCollection->init(Object(UsersController))
#2 /Applications/MAMP/htdocs/kuratur-120813/lib/Cake/Routing/Dispatcher.php(100): Controller->constructClasses()
#3 /Applications/MAMP/htdocs/kuratur-120813/lib/Cake/Routing/Dispatcher.php(86): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#4 /Applications/MAMP/htdocs/kuratur-120813/app/webroot/index.php(98): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
```

What I did:
Unzipped the debug_kit-master.zip into Plugin/DebugKit. 

bootstrap.php - uncommented `CakePlugin::load('DebugKit');`

core.php -  `Configure::write('debug',1 );`

composer.json looks like this - but I also got the error when not including the  `"cake/php/debug_kit": 2.2.*"`   line:    

```
"require": {
        "php": ">=5.3.0",
        "composer/installers": "*",
        "cakephp/debug_kit": "2.2.*"
    }
```

The   ToolbarComponent.php   file with DebugKit   contains this:

```
class ToolbarComponent extends Component implements CakeEventListener {
```

So, it doesn't seem like I should add  `class ToolbarComponent extends Component {`   to that?

I made a copy of ToolbarComponent.php  from the plugin files and added it to app/Controller/Component/  (per the error), but still get the exact same error.

Appreciate any help. Thanks!

**Comment by Josbrafe** [comment]
how i resolved my toolbarcomponent issue:
I use cakephp: 2.6.3, I downloaded version 3.0.
i followed the basic setup as instructed by articles online for installing debugkit.
which didn't work immediately for me. 

after much research i deduct that issue is related to compatibility of versions. 
i did deleted the folder: DebugKit created under app/plugins
installed composer.
restarted my wamp server
right-click on the cakephp: www/cakephp
selected: composer install
composer created a new debugkit folder under: www/cakephp/plugin/
which i moved the folder to: app/plugin/
cakephp was able to detect the new plugin.

**Comment by ashurai123** [comment]
I encountered same problem, and fixed it. the fixed was only permission issue on DebugKit Directory, give it permission 755 and restart your server, it will start executing. Thanks
