### ISSUE TITLE
Where is EXPLAIN in 3.x version?

### ISSUE THREAD

**Issue by BassemN** [cakephp/debug_kit#464]
I can't see the EXPLAIN button on SQL queries, It was visible in version 2.x

**Comment by dereuromark** [comment]
Refs https://github.com/cakephp/debug_kit/pull/439

**Comment by BassemN** [comment]
Why this PR closed and what is the roadmap for this essential feature when debugging? and how can I implement it for now into my app?

**Comment by chinpei215** [comment]
@BassemN Because my proposed PR (https://github.com/cakephp/cakephp/pull/9421) wasn't approved.

As a background, I opened the PR after I saw [this tweet](https://twitter.com/shinichi399/status/770826994137255936). You would be surprised if you tweeted something about CakePHP and if it realized a few days later. However, too much time has passed after he tweeted. There is no longer surprise. So it was difficult to keep up my motivation and to find time.

But recently, @thinkingmedia  blew a new wind in the above PR. You might be able to see the EXPLAIN button on the SQL log panel, in the not-so-distant future.

**Comment by BassemN** [comment]
@dereuromark @chinpei215 @thinkingmedia  I think this is a critical issue and we should implement it ASAP

**Comment by markstory** [comment]
@BassemN Pull requests are welcome :smile:

**Comment by dereuromark** [comment]
@BassemN I do not agree with your assessment. This is never a critical feature, a "nice to have" one maybe.
You can right now already copy and paste the queries into any SQL tool of your choice - and get the desired results.
But of course a PR here to implement it would be very welcome none the less, as others mentioned.

**Comment by BassemN** [comment]
@markstory @dereuromark  I'm not expert like you in CakePHP but I see that @chinpei215 already did a great job here #439 and I hope to see this merged.

**Comment by thinkingmedia** [comment]
@BassemN the database layer used in Cake 3 was completely rewritten. Unfortunately this feature requires that changes are made to the database drivers, and any make changes in that part of the code is something we do slowly and carefully.

There is a project for database improvements in the Cake 3.4 release. This feature has been schedule in the back log of things to do.

https://github.com/cakephp/cakephp/projects/2

If this is of interest to you, please subscribe to the related issues. I have a few other issues to finish before I could even begin on this.

That's the best I can do.

**Comment by BassemN** [comment]
@thinkingmedia Thank you for your clear and helpful explanation for this feature roadmap :+1:

**Comment by othercorey** [comment]
Doesn't look like we're going to implement this. Users can provide a PR if they want to add it.
