### ISSUE TITLE
PHP 8: deprecationWarning() is shown as source of all deprecations

### ISSUE THREAD

**Issue by othercorey** [cakephp/debug_kit#845]
```
CAKE/Core/functions.php:322

QueryExpression::addCase() is deprecated, use case() instead.
```

All deprecations are shown originating in deprecationWarning() even though the file shown in the message is the correct source. 

Can we list the source file instead of functions.php?

**Comment by LordSimal** [comment]
One example of such a "wrong" deprecation message can be seen in https://github.com/dereuromark/cakephp-queue/pull/310

It looks like its a deprecation caused by CakePHP core but actually its a plugin issue.

**Comment by LordSimal** [comment]
As @othercorey already mentioned in https://github.com/cakephp/cakephp/issues/15195 the removal of the context parameter in PHP's `set_error_handler` function causes this issue. https://www.php.net/manual/en/function.set-error-handler.php

So we now have to find some other way how to detect the root cause of the deprecation warnings.

**Comment by LordSimal** [comment]
At least for the Time and Date deprecation warnings I though a temporary fix would be to adjust the `deprecationWarning()` calls inside those classes to not pass 0 as a `$stackFrame` and therefore show the cause of the deprecation in the message like that:

![image](https://user-images.githubusercontent.com/9105243/141518786-731dc4dd-a5e5-4c4c-8a3b-74e931e68ea7.png)

Instead of the current state:

![image](https://user-images.githubusercontent.com/9105243/141518597-79a2430d-bd9c-4641-b276-8ecf5ffcc09c.png)

but this spectacularly breaks the tests for the core... 😞

**Comment by othercorey** [comment]
The issue is the `functions.php` title for each entry.

**Comment by LordSimal** [comment]
so the current "solution" would be to remove the `deprecationWarning()` helper function and each plugin has to do "native" deprecation warnings. Then the current implementation would work.

**Comment by markstory** [comment]
Re-opening as this problem isn't entirely solved. The remaining problems are tied to the `stackOffset` of the `deprecationWarning()` call. When this occurs in PHP8+ the listed location is still within the framework and not in userland code.

**Comment by saeideng** [comment]
#854 solved the `stackOffset` issue
