### ISSUE TITLE
DebugKit's iframe height is extremely small and adds scroll bars on medium resolution monitors

### ISSUE THREAD

**Issue by johnnysprone** [cakephp/debug_kit#888]
DebugKit's iframe height is extremely small and adds scroll bars on medium resolution monitors, not allowing full display of options. The problem was identified when using a notebook with a 1366 x 768 resolution monitor. Removing the CSS property "overflow: auto" from the ".c-toolbar" class used in `<ul id="toolbar" />` solves the problem.

Problem:
![1](https://user-images.githubusercontent.com/101278259/188660555-c76fd25f-fbda-415a-b553-1eb2d4affef6.jpg)

Solves the problem:
![2](https://user-images.githubusercontent.com/101278259/188660581-4fd005cc-8ca8-4f4a-9eb5-f94eb9902f6c.jpg)

**Comment by LordSimal** [comment]
@johnnysprone I can reproduce your problem and have a proposed solution:

Instead of `overflow: auto` try a `overflow: hidden`
With that no scrollbar will appear and instead the expected behavior only persists where users have to use the arrows on the left side to scroll through the tabs.

Would that solve your problem?
