### ISSUE TITLE
DebugKit not loading with CSP rule `strict-dynamic`

### ISSUE THREAD

**Issue by gerhard-lechner** [cakephp/debug_kit#943]
When I set up a fresh copy of CakePHP 4.4 and add the `CspMiddleware` in `Application.php` with the following settings ...

```
new CspMiddleware(['script-src' => ['strict-dynamic' => true]], ['scriptNonce' => true])
```

... the browser doesn't load DebugKit.

Error message:

> Refused to load the script 'http://localhost:8080/cakephp/debug_kit/js/inject-iframe.js?1674622148' because it violates the following Content Security Policy directive: "script-src 'nonce-24URd7b/3/ZF1wlidPdZCe53' 'strict-dynamic'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

Adding `'self' => true` to the `script-src` rule doesn't help as with `strict-dynamic` the host list gets ignored.

Adding a script via the HtmlHelper works flawlessly, because `HtmlHelper::script()` sets the nonce in the `<script>` tag correctly, whereas DebugKit's `ToolbarService::injectScripts()` doesn't take nonce into consideration.

I prefer to use the same CSP settings in development as in production to make sure everything works correctly, so I think DebugKit should also work with the CSP settings mentioned above.

**Comment by gerhard-lechner** [comment]
Thanks for addressing this issue. However, I'm not sure the fix actually solves the problem. I still get a `<script>` tag without a nonce when I load DebugKit in my application.

DebugKit is added in `Application::bootstrap()`, before `Application::middleware()` is called and CSP rules are set up. When I do a `pr($request);` in `debug_kit/src/ToolbarService::injectScripts()`, the Request Object has no `cspScriptNonce` set. However, if I do `pr($this->request);` in any Controller of my application, the `cspScriptNonce` IS set.

Maybe the test case, where the `cspScriptNonce` gets set in the Request Object manually isn't quite the same to what happens when the actual application gets loaded? Logically I would think that `$request` in DebugKit and `$this->request` in my application's Controller should refer to the same object, but as far as my debugging went, I think that's not the case?

**Comment by LordSimal** [comment]
The problem is the fact, that we inject the DebugKitMiddleware at the first position
https://github.com/cakephp/debug_kit/blob/4.x/src/Plugin.php#L71

Plugin Middleware's are always run after application middlewares, so you are basically unable to inject the CspMiddleware before the DebugKitMIddleware in the `middleware()` method.

But you can listen to the `Server.buildMiddleware` event and add that Middleware at the very beginning.
```
$this->getEventManager()->on(
    'Server.buildMiddleware',
    function (EventInterface $event, MiddlewareQueue $middleware) {
        $middleware
            ->insertAt(0, new CspMiddleware(['script-src' => ['strict-dynamic' => true]], ['scriptNonce' => true]));
    }
);
```

Add this at the end of your `bootstrap()` method in your `src/Application.php`

Then it should work fine

**Comment by markstory** [comment]
> Logically I would think that $request in DebugKit and $this->request in my application's Controller should refer to the same object, but as far as my debugging went, I think that's not the case?

It is and isn't the same request object. Because requests are immutable, as attributes/headers/body are added, new request instances are created. This combined with the middleware insertion point is resulting in the nonce missing when the toolbar is injected.  We might be able to extract the nonce using regex patterns 🤔 It will be a bit hacky but it should work.

**Comment by gerhard-lechner** [comment]
> Because requests are immutable, as attributes/headers/body are added, new request instances are created.

I see, that makes sense of course. Speaking about hacky solutions - storing the script / style nonce in a constant might not be a desirable solution either, I guess?

**Comment by gerhard-lechner** [comment]
Just realised that getting the request object via `Router::getRequest()` in `debug_kit/src/ToolbarService::injectScripts()` actually does the trick.
